library(caret)
library(e1071)
library()
a<-read.csv("C:/Users/voraa/Desktop/irisdata.csv")
b<-read.csv("C:/Users/voraa/Desktop/irisdata.csv")
c<-read.csv("C:/Users/voraa/Desktop/irisdata.csv")
a$species<-factor(a$species, levels = c("setosa","versicolor","virginica"), labels = c(1,0,0))
table(a$species)
c$species<-factor(c$species, levels = c("setosa","versicolor","virginica"), labels = c(0,0,1))
table(c$species)
b$species<-factor(b$species, levels = c("setosa","versicolor","virginica"), labels = c(0,1,0))
table(b$species)
names(a)
lg.fit1<-glm(species~sepal_length+sepal_width+petal_length+petal_width,data=a,family = "binomial")
summary(lg.fit1)
trc<-trainControl(method="repeatedcv",number=10,savePredictions = TRUE)
mod.fit<-train(species~sepal_length+sepal_width+petal_length+petal_width,data=a,family="binomial",trcontrol=trc)
pred=predict(mod.fit,newdata = a)
confusionMatrix(data=pred,a$species)
