train<-read.csv("C:/Users/voraa/Desktop/train.csv")
test<-read.csv("C:/Users/voraa/Desktop/test.csv")
train$pclass<-as.ordered(train$pclass)
test$pclass<-as.ordered(test$pclass)
library(Amelia)
dim(test)
missmap(test, main = "Missing Values vs. Observed")
training <- subset(train, select = c(1,2,3,4,5,6,7,8,9,10,11,12,14))
testing <- subset(test, select = c(1,2,3,4,5,6,7,8,9,10,11,13))
missmap(training, main = "Missing Values vs. Observed")
missmap(testing, main = "Missing Values vs. Observed")
training$age[is.na(training$age)] = mean(training$age, na.rm=TRUE)
testing$age[is.na(testing$age)] = mean(testing$age, na.rm=TRUE)
lg.fit<-glm(survived~.-name-ticket-cabin-home.dest,data =training,family ="binomial")
summary(lg.fit)
str(train)
lg.fit1<-glm(survived~boat+sex+pclass,data =training,family ="binomial")
summary(lg.fit1)
exp(coef(lg.fit1))
y_predict<-predict(lg.fit1,newdata= testing,type="response")
y_predict
y_predict1<-ifelse(y_predict>0.5,"1","0")
y_predict1
